development:
  host: localhost
  database: sidblog_development

test:
  host: localhost
  database: sidblog_test

# set these environment variables on your prod server
production:
  uri: <%= ENV["MONGOHQ_URL"] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
